<?php
/**
 * @file
 * Produce default feeds block and position them in the zone postscript
 * 
 */

/*
 * Implements hook_block_info()
 */
function npt_feeds_block_info_alter(&$blocks, $theme, $code_blocks) {
  $result = db_query('SELECT f.fid, f.title, f.url, f.refresh, f.checked, f.link, f.description, f.hash, f.etag, f.modified, f.image, f.block FROM {aggregator_feed} f ORDER BY f.fid');
  $gbif_feed = array();
  foreach ($result as $feed) {
    if ($feed->title == 'GBIF News' || $feed->title == 'GBIF Latest Online Resources') {
      $delta = 'feed-' . $feed->fid;
      $gbif_feed[$feed->fid]['delta'] = $delta;
      $gbif_feed[$feed->fid]['region'] = 'postscript_first';
      $gbif_feed[$feed->fid]['status'] = 1;
    }
    if ($feed->title == 'GBIF Latest Online Resources') {
      $delta = 'feed-' . $feed->fid;
      $gbif_feed[$feed->fid]['delta'] = $delta;
      $gbif_feed[$feed->fid]['region'] = 'postscript_second';
      $gbif_feed[$feed->fid]['status'] = 1;
    }
  }

  switch ($theme) {
    case 'gbifwhite':
      foreach ($gbif_feed as $feedblock) {
        $dlt = $feedblock['delta'];
        $rgn = $feedblock['region'];
        $blocks['aggregator'][$dlt]['status'] = 1;
        $blocks['aggregator'][$dlt]['region'] = $rgn;
      }
      break;
  }
}