<?php

/**
 * @file
 * This module talks to the GBIF OGC Map service to get map images.
 * 
 */

/**
 * Implementats hook_help().
 */

function gbif_map_help($path, $arg) {
  if ($path == 'admin/help#gbif_map') {
    return t('This module talks to the GBIF OGC Map service to get map images.');
  }
}

/**
 * Implementation of hook_menu().
 */

function gbif_map_menu() {
  $items = array();

  // Change the description of a form element.
  $items['gbif_map'] = array(
    'title' => 'Country Data Maps',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gbif_map'),
    'access callback' => TRUE,
    'access arguments' => array('access content'),
    'weight' => 0,
  );

  return $items;
}

/**
 * Simple form whose ajax-enabled 'changethis' member causes a text change
 * in the description of the 'replace_textfield' member.
 * See @link http://drupal.org/node/262422 Form API Tutorial @endlink
 */
function gbif_map($form, &$form_state) {
  $form = array();
  $form['changethis'] = array(
    '#title' => t("This page would provide a geographical summary of the data that is currently available for your country through the GBIF portal.<br>The finished version would be interactive so you could zoom in and select a square to find out what has been recorded there.<br>As a demonstration of accessing GBIF OGC Web Services, there are some countries available to choose."),
    '#type' => 'select',
    '#options' => array(
      '0' => 'Choose one country',
      'AU' => 'Australia',
      '26' => 'Benin',
      'DK' => 'Denmark',
      '84' => 'Guinea',
      'FR' => 'France',
      '113' => 'Kenya',
      '139' => 'Madagascar',
      '212' => 'Togo',
      'TW' => 'Taiwan',
      '226' => 'Uganda',
      'US' => 'United States of America',
    ),
    '#ajax' => array(
      // #ajax has two required keys: callback and wrapper.
      // 'callback' is a function that will be called when this element changes.
      'callback' => 'gbif_map_callback',
      // 'wrapper' is the HTML id of the page element that will be replaced.
      'wrapper' => 'replace_textfield_div',
      'method' => 'replace',
      // There are also several optional keys - see ajax_example_autocheckboxes
      // below for details on 'method', 'effect' and 'speed' and
      // ajax_example_dependent_dropdown for 'event'.
     ),
  );

  // This entire form element will be replaced whenever 'changethis' is updated.
  $form['replace_textfield'] = array(
    // The prefix/suffix provide the div that we're replacing, named by
    // #ajax['wrapper'] above.
    '#prefix' => '<div id="replace_textfield_div">',
    '#suffix' => '</div>',
  );
  
  $bbox = array();
  $bbox = array(
    'AU' => "94,-47,174,-7",
    '26' => "-37,-6,43,34",
    'DK' => "-29,36,51,76",
    '84' => "-51,-10,29,30",
    'FR' => "-37,27,43,67",
    '113' => "-2,-20,78,20",
    '139' => "7,-38,87,2",
    '212' => "-39,-11,41,29",
    'TW' => "81,4,161,44",
    '226' => "-8,-18,72,22",
    'US' => "-180,-90,180,90",
  );
  
  // An AJAX request calls the form builder function for every change.
  // We can change how we build the form based on $form_state.
  if (!empty($form_state['values']['changethis'])) {
    $country_code = $form_state['values']['changethis'];
    //$markup_string = t("Say why you chose '@value'", array('@value' => $form_state['values']['changethis']));
    $map_img_link = "http://ogc.gbif.org/wms?request=GetMap&bgcolor=0x666698&styles=,,,&layers=gbif:country_fill,gbif:tabDensityLayer,gbif:country_borders,gbif:country_names&srs=EPSG:4326&filter=()(<Filter><PropertyIsEqualTo><PropertyName>url</PropertyName><Literal><![CDATA[http://data.gbif.org/maplayer/country/".$country_code."]]></Literal></PropertyIsEqualTo></Filter>)()()&width=721&height=362&Format=image/png&bbox=".$bbox[$country_code];
    $form['replace_textfield']['#markup'] = '<img src="'. $map_img_link .'"/><br/>';
  }

  return $form;
}

/**
 * Callback for ajax_example_simplest.
 *
 * On an ajax submit, the form builder function is called again, then the $form
 * and $form_state are passed to this callback function so it can select which
 * portion of the form to send on to the client.
 *
 * @return renderable array (the textfield element)
 */
function gbif_map_callback($form, $form_state) {
  // The form has already been submitted and updated. We can return the replaced
  // item as it is.
  return $form['replace_textfield'];
}