<?php
/**
 * @file
 * Position default blocks in gbifwhite2012 theme.
 *
 */

/**
 * Implements hook_block_info().
 */
function npt_blocks_block_info() {
  $blocks['credit_npt'] = array(
    'info' => t('NPT Startup credit'),
    'region' => 'credit_second',
    'weight' => 1,
    'theme' => NPTSTARTUP_THEME,
    'status' => 1,
  );
  $blocks['how_to_publish'] = array(
    'info' => t('How to publish data through the GBIF network'),
    'region' => 'sidebar_second',
    'weight' => 1,
    'theme' => NPTSTARTUP_THEME,
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => 'taxonomy/term/*'
  );
  $blocks['credit_orgs'] = array(
    'info' => t('ViBRANT and GBIF credit'),
    'region' => 'credit_stretch',
    'weight' => 1,
    'theme' => NPTSTARTUP_THEME,
    'status' => 1,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function npt_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'credit_npt':
      $content = '<span class="nptcredit"><p><a href="http://community.gbif.org/pg/groups/3507/nodes-portal-toolkit-npt/">' . t('The NPT Project') . '</a></p></span>';
      $block['content'] = array(
        '#markup' => $content
      );
      break;
    case 'how_to_publish':
      $participant_shortname = variable_get('gbif_participant_shortname');
      $participant_node = variable_get('gbif_participant_node');
      $node_value = explode('-', $participant_node);
      $iso_a2 = $node_value[0];
      $country = $node_value[1];

      $howto_publish_text = l(t('How to publish data through the GBIF network?'), variable_get('howto_publish_page'));
      $country_page = t('@country on the !portal_link.', array(
        '@country' => $country,
        '!portal_link' => l(t('GBIF Data Portal'), 'http://data.gbif.org/countries/' . strtoupper($iso_a2))
      ));
      
      $links_for_intro = array(
        $howto_publish_text,
        $country_page
      );
      $block['content'] = array(
        '#theme' => 'item_list',
        '#items' => $links_for_intro
      );
      break;
    case 'credit_orgs':
      $path = drupal_get_path('module', 'npt_blocks');
      $options = array(
        'html' => TRUE,
        'absolute' => TRUE
      );
      $links = array(
        l(theme('image', array(
          'path' => $path . '/images/vibrant_44.png',
          'alt' => 'ViBRANT logo',
          'title' => 'ViBRANT'
        )), 'http://vbrant.eu/', $options),
        l(theme('image', array(
          'path' => $path . '/images/gbif_48.png',
          'alt' => 'GBIF logo',
          'title' => 'GBIF'
        )), 'http://www.gbif.org/', $options)
      );
      $block['content'] = array(
        '#theme' => 'item_list',
        '#items' => $links
      );
      break;
  }
  return $block;
}

/**
 * Implementation of hook_views_api().
 */
function npt_blocks_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'npt_blocks') . '/views'
  );
}

/**
 * Implements hook_ctools_plugin_api()
 */
function npt_blocks_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'context') {
    return array('version' => '3');
  }
  if ($module == 'delta' && $api == 'delta') {
    return array('version' => '3');
  }
}