<?php
define('NPTSTARTUP_THEME_NAME', 'gbifwhite2012');


/**
 * 
 * Implentation of hook_block_info_alter
 * Adjust the blocks for this theme
 * @param array $blocks
 * @param string $theme
 * @param array $code_blocks
 */
/* 
function gbif_nptblocks_block_info_alter(&$blocks, $theme, $code_blocks){
  switch($theme){
    case 'gbif2012':
      // Move the search box to the search region
      $blocks['search']['form']['region'] = 'search';
      break;
    case 'gbifwhite2012':
      // Move the search box to the search region
      $blocks['search']['form']['region'] = 'search';
      break;
  }
}
*/

/**
 * Implements hook_block_info().
 */
function npt_blocks_block_info() {
  $blocks['credit_npt'] = array(
    'info' => t('NPT Startup credit'),
    'region' => 'credit_second',
    'weight' => 1,
    'theme' => NPTSTARTUP_THEME_NAME,
    'status' => 1
  );
  $blocks['credit_orgs'] = array(
    'info' => t('ViBRANT and GBIF credit'),
    'region' => 'credit_stretch',
    'weight' => 1,
    'theme' => NPTSTARTUP_THEME_NAME,
    'status' => 1
  );
  $blocks['gbif_ogc_map'] = array(
    'info' => t('GBIF Species Distribution'),
    'region' => 'content',
    'weight' => 0,
    'theme' => NPTSTARTUP_THEME_NAME,
    'status' => 0
  );
  $blocks['howto_publish'] = array(
    'info' => t('How to publish data in the GBIF network'),
    'region' => 'sidebar_second',
    'weight' => 0,
    'theme' => NPTSTARTUP_THEME_NAME,
    'status' => 0
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function npt_blocks_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'credit_npt':
      $content = '<span class="nptcredit"><p><a href="http://community.gbif.org/pg/groups/3507/nodes-portal-toolkit-npt/">' . t('The NPT Project') . '</a></p></span>';
      $block['content'] = array(
        '#markup' => $content
      );
      break;
    case 'credit_orgs':
      $path = drupal_get_path('module', 'npt_blocks');
      $options = array(
        'html' => true,
        'absolute' => true
      );
      $links = array(
        l(theme('image', array(
          'path' => $path . '/images/vibrant_44.png',
          'alt' => 'ViBRANT logo',
          'title' => 'ViBRANT'
        )), 'http://vbrant.eu/', $options),
        l(theme('image', array(
          'path' => $path . '/images/gbif_48.png',
          'alt' => 'GBIF logo',
          'title' => 'GBIF'
        )), 'http://www.gbif.org/', $options)
      );
      $block['content'] = array(
        '#theme' => 'item_list',
        '#items' => $links
      );
      break;
    case 'gbif_ogc_map':
      $entity_id = arg(2);
      $result = db_query('SELECT guid FROM {feeds_item} WHERE entity_type = :entity_type AND entity_id = :entity_id', array(':entity_type' => 'taxonomy_term', ':entity_id' => $entity_id))->fetch();
      $guid = $result->guid;
      $map_url = "http://ogc.gbif.org/wms?request=GetMap&bgcolor=0x666698&styles=,,&layers=gbif:country_fill,gbif:tabDensityLayer,gbif:country_borders&srs=EPSG:4326&filter=()(%3CFilter%3E%3CPropertyIsEqualTo%3E%3CPropertyName%3Eurl%3C/PropertyName%3E%3CLiteral%3E%3C!%5BCDATA%5Bhttp%3A%2F%2Fdata.gbif.org%2Fmaplayer%2Ftaxon%2F". $guid . "%5D%5D%3E%3C/Literal%3E%3C/PropertyIsEqualTo%3E%3C/Filter%3E)()&width=700&height=320&Format=image/png&bbox=-180,-90,180,90";
      
      $content = '<div class="gbif_map"><img src="' . $map_url . '" /></div>';
      
      /*
      $block['content'] = array(
        '#markup' => $content
      );
      */
        $block['content'] = '<h2 class="block-title">GBIF Global Distribution</h2>' .theme('gm3_map', array(
       'map' => array(
         'libraries' => array(
           'eol_gbif_maps_overlay' => array(
             'module' => 'eol_gbif_maps',
             'taxon_id' => $guid
           )
         )
       )
      ));
      
      break;
      
  }
  return $block;
}