<?php

/**
 * Implementation of hook_gm3_alter().
 */
function npt_maps_gm3_map_alter(&$map){
  // Add the country mask to a google map on taxonomy term pages only.
  if($term = menu_get_object('taxonomy_term', 2)){

    $map['libraries']['npt_country_mask'] = array(
      'module' => 'npt_maps',
    );
  }
}

/**
 * Implementation of hook_library().
 */
function npt_maps_library(){
  // Prepare coordinate and polygon information.
  // The country is first decided by the Participant setting.
  $gbif_participant_settings = variable_get('gbif_participant_settings');
  $iso2 = $gbif_participant_settings['node_country'];
  $iso3 = _npt_startup_get_iso3_by_iso2($gbif_participant_settings['node_country']);
  
  // Getting the WKT from gm3_region_data table.
  // @TODO: Need take into account that if this returns multiple results.
  $polygon_results = db_select('gm3_region_data', 'g')
               ->fields('g', array('polygons'))
               ->condition('iso_code', $iso2)
               ->execute();
  $row_count = $polygon_results->rowCount();
  $result = $polygon_results->fetchAll();
  
  if ($row_count > 0) {
    gm3_load_geophp();

    // If there are more than one polygon, combine them as one multipolygon.
    $unified_multipolygon = array();
    
    if ($row_count > 1) {
      foreach ($result as $k) {
        $geometry = geoPHP::load($k->polygons);
        if ($geometry->getGeomType() == 'Polygon') {
          array_push($unified_multipolygon, $geometry);
        }
        elseif ($geometry->getGeomType() == 'MultiPolygon') {
          $polygons = $geometry->getComponents();
          foreach ($polygons as $polygon) {
            array_push($unified_multipolygon, $polygon);
          }
        }
      }
    }
    elseif ($row_count == 1) {
      $geometry = geoPHP::load($result[0]->polygons);
      if ($geometry->getGeomType() == 'Polygon') {
        array_push($unified_multipolygon, $geometry);
      }
    }

    // initialise an empty geometry
    $num = count($unified_multipolygon);
    $poly1 = $unified_multipolygon[0];
    $poly2 = $unified_multipolygon[1];
    $combined_poly = $poly1->union($poly2);
    
    for ($i = 1; $i < $num; $i++) {
      $combined = $combined->union($unified_multipolygon[$i]);
    }
    
    $wkt = $combined->out('wkt');

    // Calculate the centre point of the polygon
    $polygon = geoPHP::load($polygon_results);
    $centroid = $polygon->getCentroid();
    $centX = round($centroid->getX(), 2);
    $centY = round($centroid->getY(), 2);

    // Determine the four points of the masking polygon. There is obviously a better way
    // to deal with the limit of 180/90 lng/lat degree. But I'll live with it for now.
    $maxX = ($centX + 60 > 179) ? 179 : $centX + 60;
    $minX = ($centX - 60 < -179) ? -179 : $centX - 60;
    $maxY = ($centY + 60 > 89) ? 89 : $centY + 60;
    $minY = ($centY - 60 < -89) ? -89 : $centY - 60;

    // The points of the masking polygon should be put in counterclockwise order.
    $outer_ring_string = $maxX . ' ' . $maxY . ',' . $minX . ' ' . $maxY . ',' . $minX . ' ' . $minY . ',' . $maxX . ' ' . $minY . ',' . $maxX . ' ' . $maxY;

    // Insert the outer polygon as the first ring in the polygon,
    // as the first ring will be the outer polygon therefore makes others holes.
    $wkt = $polygon_results;

    return array(
      'npt_country_mask' => array(
        'title' => t('Country mask'),
        'version' => '0.1',
        'js' => array(
          array(
            'data' => drupal_get_path('module', 'npt_maps') . "/js/npt_maps.js"
          ),
          array(
            'data' => array(
              'npt_maps' => array(
                'settings' => array(
                  'mask' => array(
                    'wkt' => $wkt
                  ),
                  'centre' => array(
                    'centX' => $centX,
                    'centY' => $centY,
                  ),
                  'outerRingString' => $outer_ring_string,
                )
              )
            ),
            'type' => 'setting'
          ),
        ),
        'css' => array(
          array(
            'data' => drupal_get_path('module', 'npt_maps') . '/css/npt_maps.css'
          )
        ),
        'dependencies' => array(
          array(
            'gm3',
          )
        )
      )
    );
  }
  else {
    // Return empty array here so the Javascript and CSS don't load.
    return array();
  }      
}